### ISSUE TITLE
`zones` should be array in example not `string`

### ISSUE THREAD

**Issue by JaeAeich** [ga4gh/task-execution-schemas#203]
```yaml 
...
zones:
  type: array
  description: |-
    Request that the task be run in these compute zones. How this string
    is utilized will be dependent on the backend system. For example, a
    system based on a cluster queueing system may use this string to define
    priorty queue to which the job is assigned.
  items:
    type: string
  example: us-west-1 ----> ["us-west-1"]
...
```
