### ISSUE TITLE
Summary endpoint.

### ISSUE THREAD

**Issue by claymcleod** [ga4gh/task-execution-schemas#215]
I'd consider adding a summary endpoint that summarizes the state of all of the tasks submitted to the server—this way, if you just want to get the counts in each state, you don't have to iterate over the entire collection of tasks (saving server bandwidth and time overall).

**Comment by uniqueg** [comment]
What's the use case exactly? Would you imagine this as an admin endpoint (total counts for tasks submitted by all users) or a user-specific one (total counts for tasks submitted by a given user)? If the former is fine for your use case and we don't consider these counts sensitive, we could add it to the service info [in the same way WES does](https://github.com/ga4gh/workflow-execution-service-schemas/blob/226f43b1fec97ad3778897a27a9651ccfa631d77/openapi/workflow_execution_service.openapi.yaml#L630-L634):

```yaml
            system_state_counts:
              type: object
              additionalProperties:
                type: integer
                format: int64
```

Not sure what happened to the description. Seems they got inadvertently lost between [1.0.0](https://github.com/ga4gh/workflow-execution-service-schemas/blob/c5406f1d3740e21b93d3ac71a4c8d7b874011519/openapi/workflow_execution_service.swagger.yaml) and [1.0.1](https://github.com/ga4gh/workflow-execution-service-schemas/blob/13f56821fb50e4b01a269354421c96c20785e909/openapi/workflow_execution_service.openapi.yaml). Anyway, it used to be:

> The system statistics, key is the statistic, value is the count of runs in that state. See the State enum for the possible keys.
